from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='001';down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 role=postgresql.ENUM('admin','manager','operator',name='userrole',create_type=False);mov=postgresql.ENUM('entry','consumption','positive_adjustment','negative_adjustment','loss','expired',name='movementtype',create_type=False)
 role.create(op.get_bind(),checkfirst=True);mov.create(op.get_bind(),checkfirst=True)
 op.create_table('users',sa.Column('id',sa.Integer,primary_key=True),sa.Column('name',sa.String(120),nullable=False),sa.Column('email',sa.String(255),unique=True,nullable=False),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('role',role,nullable=False,server_default='operator'),sa.Column('active',sa.Boolean,nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table('products',sa.Column('id',sa.Integer,primary_key=True),sa.Column('name',sa.String(150),nullable=False),sa.Column('sku',sa.String(80),unique=True),sa.Column('category',sa.String(100)),sa.Column('unit',sa.String(30),nullable=False),sa.Column('minimum_stock',sa.Numeric(14,3),nullable=False,server_default='0'),sa.Column('controls_expiration',sa.Boolean,nullable=False,server_default=sa.true()),sa.Column('active',sa.Boolean,nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table('batches',sa.Column('id',sa.Integer,primary_key=True),sa.Column('product_id',sa.Integer,sa.ForeignKey('products.id'),nullable=False),sa.Column('batch_number',sa.String(80),nullable=False),sa.Column('initial_quantity',sa.Numeric(14,3),nullable=False),sa.Column('current_quantity',sa.Numeric(14,3),nullable=False),sa.Column('manufacture_date',sa.Date),sa.Column('expiration_date',sa.Date),sa.Column('received_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('supplier',sa.String(160)),sa.Column('unit_cost',sa.Numeric(14,2)),sa.UniqueConstraint('product_id','batch_number'))
 op.create_table('stock_movements',sa.Column('id',sa.Integer,primary_key=True),sa.Column('product_id',sa.Integer,sa.ForeignKey('products.id'),nullable=False),sa.Column('batch_id',sa.Integer,sa.ForeignKey('batches.id'),nullable=False),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id'),nullable=False),sa.Column('movement_type',mov,nullable=False),sa.Column('quantity',sa.Numeric(14,3),nullable=False),sa.Column('reason',sa.String(200)),sa.Column('department',sa.String(120)),sa.Column('notes',sa.Text),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
def downgrade():
 op.drop_table('stock_movements');op.drop_table('batches');op.drop_table('products');op.drop_table('users');postgresql.ENUM(name='movementtype').drop(op.get_bind(),checkfirst=True);postgresql.ENUM(name='userrole').drop(op.get_bind(),checkfirst=True)
